import {StyleSheet} from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FAF8FF',
    },
    scrollContainer: {
        flexGrow: 1,
        alignItems: 'center',
        padding: 20,
        paddingBottom: 40,
    },
    header: {
        fontSize: 28,
        fontWeight: '700',
        color: '#1E1E2D',
        marginBottom: 20,
        marginTop: 10,
    },
    bikeImage: {
        width: 120,
        height: 120,
        marginBottom: 40,
        resizeMode: 'contain',
    },
    infoBox: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 20,
        width: '100%',
        marginBottom: 30,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
        elevation: 3,
    },
    label: {
        fontSize: 14,
        fontWeight: '600',
        color: '#444',
    },
    value: {
        fontSize: 16,
        color: '#000',
        fontWeight: '500',
    },
    button: {
        backgroundColor: '#4A90E2',
        paddingVertical: 34,
        marginTop: 100,
        paddingHorizontal: 40,
        borderRadius: 30,
        elevation: 2,
    },
    buttonRed: {
        backgroundColor: '#FF3B30',
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: 17,
        fontWeight: '600',
        textAlign: 'center',
    },
    riepilogoContainer: {
        alignItems: 'center',
        width: '100%',
    },
    riassunto: {
        fontSize: 20,
        fontWeight: '700',
        color: '#1E1E2D',
        marginTop: 10,
        textAlign: 'center',
    },
    riepilogoDesc: {
        fontSize: 14,
        color: '#555',
        textAlign: 'center',
        marginTop: 5,
        paddingHorizontal: 20,
    },
    feedbackSection: {
        width: '100%',
        marginTop: 20,
    },
    feedbackButton: {
        backgroundColor: '#4A90E2',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 25,
        alignSelf: 'center',
        elevation: 2,
    },
    feedbackButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
    },
    feedbackContainer: {
        width: '100%',
        backgroundColor: '#FFFFFF',
        borderRadius: 15,
        padding: 20,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
        elevation: 3,
    },
    feedbackTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1E1E2D',
        marginBottom: 15,
        textAlign: 'center',
    },
    feedbackInput: {
        width: '100%',
        minHeight: 100,
        borderColor: '#E0E0E0',
        borderWidth: 1,
        borderRadius: 12,
        padding: 15,
        fontSize: 16,
        backgroundColor: '#F9F9F9',
        marginBottom: 8,
    },
    characterCount: {
        fontSize: 12,
        color: '#888',
        textAlign: 'right',
        marginBottom: 20,
    },
    feedbackButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 10,
    },
    cancelFeedbackButton: {
        flex: 1,
        backgroundColor: '#F0F0F0',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 25,
        elevation: 1,
    },
    cancelFeedbackButtonText: {
        color: '#666',
        fontWeight: '600',
        fontSize: 16,
        textAlign: 'center',
    },
    sendFeedbackButton: {
        flex: 1,
        backgroundColor: '#28a745',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 25,
        elevation: 2,
    },
    sendFeedbackButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
        textAlign: 'center',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalBox: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 25,
        width: '80%',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.15,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 3 },
        elevation: 5,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#1E1E2D',
        marginBottom: 10,
        textAlign: 'center',
    },
    modalText: {
        fontSize: 16,
        color: '#333',
        marginBottom: 20,
        textAlign: 'center',
    },
    modalButton: {
        backgroundColor: '#4A90E2',
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 25,
        minWidth: 120,
        alignItems: 'center',
    },
    modalButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
});
