import {StyleSheet} from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0a0a0a',
        paddingHorizontal: 20,
    },
    header: {
        alignItems: 'center',
        marginTop: 60,
        marginBottom: 40,
    },
    title: {
        fontSize: 28,
        fontWeight: '700',
        color: '#ffffff',
        textAlign: 'center',
        marginBottom: 8,
        letterSpacing: 0.5,
    },
    subtitle: {
        fontSize: 16,
        color: '#888888',
        textAlign: 'center',
        fontWeight: '400',
    },
    mainContent: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    faceContainer: {
        position: 'relative',
        marginBottom: 50,
    },
    faceBorder: {
        width: 200,
        height: 200,
        borderRadius: 100,
        borderWidth: 3,
        borderColor: '#00d4ff',
        padding: 8,
        shadowColor: '#00d4ff',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 10,
    },
    faceInner: {
        flex: 1,
        borderRadius: 92,
        backgroundColor: '#1a1a1a',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#333333',
    },
    faceIcon: {
        fontSize: 64,
    },
    corner: {
        position: 'absolute',
        width: 20,
        height: 20,
        borderColor: '#00d4ff',
        borderWidth: 3,
    },
    topLeft: {
        top: -10,
        left: -10,
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderTopLeftRadius: 8,
    },
    topRight: {
        top: -10,
        right: -10,
        borderLeftWidth: 0,
        borderBottomWidth: 0,
        borderTopRightRadius: 8,
    },
    bottomLeft: {
        bottom: -10,
        left: -10,
        borderRightWidth: 0,
        borderTopWidth: 0,
        borderBottomLeftRadius: 8,
    },
    bottomRight: {
        bottom: -10,
        right: -10,
        borderLeftWidth: 0,
        borderTopWidth: 0,
        borderBottomRightRadius: 8,
    },
    instructionsContainer: {
        width: '100%',
        maxWidth: 320,
    },
    instructionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: 16,
        textAlign: 'center',
    },
    instructionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
        paddingHorizontal: 16,
    },
    instructionNumber: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#00d4ff',
        color: '#000000',
        fontSize: 14,
        fontWeight: '700',
        textAlign: 'center',
        lineHeight: 24,
        marginRight: 12,
    },
    instructionText: {
        flex: 1,
        fontSize: 14,
        color: '#cccccc',
        lineHeight: 20,
    },
    buttonContainer: {
        width: '100%',
        alignItems: 'center',
        paddingBottom: 40,
    },
    button: {
        width: '100%',
        maxWidth: 300,
        backgroundColor: '#00d4ff',
        borderRadius: 16,
        paddingVertical: 18,
        paddingHorizontal: 24,
        shadowColor: '#00d4ff',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 8,
    },
    buttonDisabled: {
        backgroundColor: '#666666',
        shadowOpacity: 0.1,
    },
    buttonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonIcon: {
        fontSize: 20,
        marginRight: 8,
    },
    buttonText: {
        color: '#ffffff',
        fontSize: 18,
        fontWeight: '600',
        textAlign: 'center',
    },
    buttonLoader: {
        marginRight: 8,
    },
    securityNote: {
        fontSize: 12,
        color: '#666666',
        textAlign: 'center',
        marginTop: 16,
        marginBottom: 18,
        fontStyle: 'italic',
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingContent: {
        alignItems: 'center',
        padding: 40,
    },
    loadingCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#1a1a1a',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 24,
        borderWidth: 2,
        borderColor: '#333333',
    },
    loadingTitle: {
        fontSize: 22,
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: 8,
    },
    loadingSubtext: {
        fontSize: 14,
        color: '#888888',
        textAlign: 'center',
        marginBottom: 24,
    },
    progressContainer: {
        width: 200,
        alignItems: 'center',
    },
    progressBar: {
        width: '100%',
        height: 4,
        backgroundColor: '#333333',
        borderRadius: 2,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: '#00d4ff',
        borderRadius: 2,
    },
});
