import {StatusBar, StyleSheet} from "react-native";

export const styles = StyleSheet.create({
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        justifyContent: 'flex-end',
        paddingTop: StatusBar.currentHeight || 44,
    },
    modal: {
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        paddingTop: 24,
        paddingBottom: 34,
        paddingHorizontal: 24,
        maxHeight: '90%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -5 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 10,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 24,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
    },
    iconContainer: {
        width: 40,
        height: 40,
        backgroundColor: '#E3F0FF',
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    iconText: {
        fontSize: 20,
    },
    title: {
        fontSize: 20,
        fontWeight: '700',
        color: '#000000',
        letterSpacing: 0.5,
        flex: 1,
        textAlign: 'center',
        marginHorizontal: 16,
    },
    closeButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#F0F0F0',
        alignItems: 'center',
        justifyContent: 'center',
    },
    closeButtonText: {
        color: '#000000',
        fontSize: 18,
        fontWeight: '600',
    },
    content: {
        gap: 16,
    },
    infoCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    availabilityCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#4A90E2',
        marginBottom: 16,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 8,
    },
    labelContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    labelIcon: {
        fontSize: 16,
        marginRight: 8,
    },
    label: {
        fontSize: 15,
        color: '#666666',
        fontWeight: '600',
    },
    value: {
        fontSize: 15,
        color: '#000000',
        fontWeight: '700',
        textAlign: 'right',
        flex: 1,
    },
    separator: {
        height: 1,
        backgroundColor: '#E0E0E0',
        marginVertical: 12,
    },
    vehiclesContainer: {
        gap: 12,
    },
    vehicleItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FAF8FF',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    vehicleIcon: {
        fontSize: 24,
        marginRight: 12,
    },
    vehicleLabel: {
        fontSize: 15,
        color: '#000000',
        fontWeight: '600',
        flex: 1,
    },
    countBadge: {
        backgroundColor: '#4A90E2',
        borderRadius: 20,
        paddingHorizontal: 12,
        paddingVertical: 6,
        minWidth: 40,
        alignItems: 'center',
    },
    countText: {
        fontSize: 14,
        color: '#FFFFFF',
        fontWeight: '700',
    },
    noDataText: {
        fontSize: 15,
        color: '#999999',
        textAlign: 'center',
        fontStyle: 'italic',
        paddingVertical: 20,
    },
    mainButton: {
        marginTop: 24,
        backgroundColor: '#4A90E2',
        borderRadius: 16,
        paddingVertical: 16,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 5,
    },
    mainButtonText: {
        color: '#FFFFFF',
        fontSize: 17,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
});