import {StyleSheet} from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        padding: 20,
    },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    amountBox: {
        width: '47%',
        aspectRatio: 1.4,
        borderRadius: 16,
        backgroundColor: '#f9f9f9',
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: 10,
        position: 'relative',
    },
    amountBoxSelected: {
        borderWidth: 2,
        borderColor: '#4AD395',
        shadowColor: '#4AD395',
        shadowOffset: {width: 0, height: 3},
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 3,
    },
    amountText: {
        fontSize: 20,
        color: '#4B2E6B',
        fontWeight: '600',
    },
    checkmark: {
        position: 'absolute',
        bottom: 8,
        right: 8,
        backgroundColor: '#4AD395',
        borderRadius: 12,
        padding: 4,
    },
    button: {
        position: 'absolute',
        bottom: 30,
        left: 60,
        right: 60,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#34C759',
        borderRadius: 12,
        flexDirection: 'row',
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 6,
        shadowOffset: {width: 0, height: 2},
        elevation: 2,
    },
    buttonText: {
        color: '#4B0055',
        fontSize: 18,
    },
    paymentContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        marginVertical: 10,
    },
    paymentMethod: {
        alignItems: 'center',
        padding: 10,
        backgroundColor: '#f2f2f2',
        borderRadius: 12,
        width: 140,
    },
    cardLabel: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 8,
    },
    cardLogo: {
        width: 80,
        height: 40,
    },
    paymentMethodSelected: {
        borderWidth: 2,
        borderColor: '#4AD395',
        shadowColor: '#4AD395',
        shadowOffset: {width: 0, height: 3},
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 3,
    },
    checkmarkPayment: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: '#4AD395',
        borderRadius: 12,
        padding: 4,
    },
    inputCustomAmount: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 8,
        paddingHorizontal: 8,
        paddingVertical: 4,
        width: 70,
        textAlign: 'center',
        color: '#4B2E6B',
    },
    divider: {
        height: 1,
        backgroundColor: '#ddd',
        marginVertical: 20,
    },
});
