package it.uniupo.studenti.mobishare.simulator.ui.components;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.util.function.Consumer;

public class SensorPanel extends JPanel {
    private JPanel panel1;
    private JButton inviaReportButton;
    private JTextField valueTextField;
    private JLabel sensorTypeLabel;

    public SensorPanel(
            String type,
            Consumer<String> sendCallback //a closure already containing the sensor and vehicle data
    ) {
        sensorTypeLabel.setText(type + ":");

        inviaReportButton.addActionListener(e -> {
            sendCallback.accept(valueTextField.getText().trim());
        });

        add(panel1);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        sensorTypeLabel = new JLabel();
        sensorTypeLabel.setText("sensor_type");
        panel1.add(sensorTypeLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        inviaReportButton = new JButton();
        inviaReportButton.setText("Invia Report");
        panel1.add(inviaReportButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        valueTextField = new JTextField();
        valueTextField.setHorizontalAlignment(10);
        valueTextField.setToolTipText("");
        panel1.add(valueTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }


}
